services:
  discollama:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DISCORD_TOKEN=
      - OLLAMA_HOST
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=phi3.5
      - REDIS_PORT=11435
    network_mode: 'host'
  redis:
    image: redis:alpine
    command: --port 11435
    restart: always
    volumes:
      - /data
    ports:
      - 11435
    network_mode: 'host'
