services:
  discollama:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - REDIS_PORT=${REDIS_PORT}
    network_mode: 'host'
  redis:
    image: redis:alpine
    command: --port ${REDIS_PORT}
    restart: always
    volumes:
      - /data
    ports:
      - ${REDIS_PORT}
    network_mode: 'host'
